name: 'Run Gradle Wrapper'
description: 'Executes Gradle Wrapper with the specified action'
inputs:
  args:
    description: 'Args to be passed to gradlew'
    required: true
  github-token:
    description: 'GitHub Token for authentication'
    required: false
  path:
    description: 'Path to the directory where the Gradle project is located (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Execute gradlew with args
      run: |
        if [ -n "${{ inputs.path }}" ]; then
          cd ${{ inputs.path }}
        fi
        chmod +x ./gradlew
        ./gradlew ${{ inputs.args }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
