name: 'Run Gradle Wrapper'
description: 'Executes Gradle Wrapper with the specified action'
inputs:
  task:
    description: 'Name of the task to execute'
    required: true
  github-token:
    description: 'GitHub Token for authentication'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash

    - name: Execute Gradle Wrapper
      run: ./gradlew "${{ inputs.task }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

