name: 'Publish Artifacts'
description: 'Publish artifacts to GitHub Packages'
inputs:
  github-token:
    description: 'GitHub Token for authentication'
    required: true
  module-name:
    description: 'Name of the module to publish'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash

    - name: Publish with Gradle
      run: |
        gradlewAction="publish"
        if [ -n "${{ inputs.module-name }}" ]; then
          gradlewAction=":${{ inputs.module-name }}:publish"
        fi
        ./gradlew $gradlewAction
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

