name: 'Publish Artifacts'
description: 'Publish artifacts to GitHub Packages'
inputs:
  github-token:
    description: 'GitHub Token for authentication'
    required: true
  project-name:
    description: 'Name of the project to publish'
    required: false
  module-name:
    description: 'Name of the module to publish'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Determine Gradle Args
      id: gradle-args
      shell: bash
      run: |
        gradleArgs="publish"
        if [ -n "${{ inputs.module-name }}" ]; then
          gradleArgs=":${{ inputs.module-name }}:publish"
        fi

        if [ -n "${{ inputs.project-name }}" ]; then
          gradleArgs="-p ${{ inputs.project-name }} $gradleArgs"
        fi

        echo "gradleArgs=$gradleArgs" >> $GITHUB_OUTPUT

    - uses: bratek20/github-actions/run-gradlew-action@main
      with:
        args: ${{ steps.gradle-args.outputs.gradleArgs }}
        github-token: ${{ inputs.github-token }}