name: 'Publish Artifacts'
description: 'Publish artifacts to GitHub Packages'
inputs:
  github-token:
    description: 'GitHub Token for authentication'
    required: true
  project-name:
    description: 'Name of the project to publish'
    required: false
  module-name:
    description: 'Name of the module to publish'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Determine Gradle Task
      id: gradle-task
      shell: bash
      run: |
        gradleTask="publish"
        if [ -n "${{ inputs.module-name }}" ]; then
          gradleTask=":${{ inputs.module-name }}:publish"
        fi

        if [ -n "${{ inputs.project-name }}" ]; then
          gradleTask="-p ${{ inputs.project-name }} $gradleTask"
        fi

        echo "gradleTask=$gradleTask" >> $GITHUB_OUTPUT

    - uses: bratek20/github-actions/run-gradlew-action@main
      with:
        task: ${{ steps.gradle-task.outputs.gradleTask }}
        github-token: ${{ inputs.github-token }}