name: 'Run Tests'
description: 'Build and test Java project with Gradle'
inputs:
  github-token:
    description: 'GitHub Token for authentication'
    required: true
  project:
    description: 'Gradle project name (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set Gradle Build Command
      id: set-gradle-command
      shell: bash
      run: |
        if [ -n "${{ inputs.project }}" ]; then
          echo "GRADLE_COMMAND=-p ${{ inputs.project }} build" >> $GITHUB_ENV
        else
          echo "GRADLE_COMMAND=build" >> $GITHUB_ENV
        fi

    - uses: bratek20/github-actions/run-gradlew-action@main
      with:
        args: ${{ env.GRADLE_COMMAND }}
        github-token: ${{ inputs.github-token }}

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/build/test-results/test/**/*.xml
