name: 'Run Tests'
description: 'Build and test Java project with Gradle'
inputs:
  github-token:
    description: 'GitHub Token for authentication'
    required: true
  project:
    description: 'Gradle project name (optional)'
    required: false
  module:
    description: 'Specific Gradle module to build (optional)'
    required: false
  path:
    description: 'Path to the directory where the Gradle project is located (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set Gradle Build Command
      id: set-gradle-command
      shell: bash
      run: |
        if [ -n "${{ inputs.module }}" ]; then
          BUILD_COMMAND=":${{ inputs.module }}:clean :${{ inputs.module }}:test"
        else
          BUILD_COMMAND="clean test"
        fi
        if [ -n "${{ inputs.project }}" ]; then
          echo "GRADLE_COMMAND=-p ${{ inputs.project }} $BUILD_COMMAND" >> $GITHUB_ENV
        else
          echo "GRADLE_COMMAND=$BUILD_COMMAND" >> $GITHUB_ENV
        fi

    - uses: bratek20/github-actions/run-gradlew-action@main
      with:
        args: ${{ env.GRADLE_COMMAND }}
        github-token: ${{ inputs.github-token }}
        path: ${{ inputs.path }}

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/build/test-results/test/**/*.xml
