name: 'Run Tests'
description: 'Build and test Java project with Gradle'
inputs:
  java-version:
    description: 'Java version to set up'
    required: true
    default: '17'
runs:
  using: 'composite'
  steps:
    - name: Check Out Code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
    - name: Grant Execute Permission to Gradlew
      run: chmod +x ./gradlew
      shell: bash
    - name: Build and Test with Gradle
      run: ./gradlew clean test
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
