name: 'Run Tests'
description: 'Build and test Java project with Gradle'
inputs:
  github-token:
    description: 'GitHub Token for authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: bratek20/github-actions/run-gradlew-action@main
      with:
        args: 'build --info'
        github-token: ${{ inputs.github-token }}

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          build/test-results/test/**/*.xml
          */build/test-results/test/**/*.xml
